// PRODUCTS DATA — generated by admin.html
// Replace the products.js file in your site with this one, then re-upload, to publish.

const PRODUCTS = [
  {
    "id": 2,
    "name": "Sample Product Two",
    "description": "A second placeholder item so you can see how the grid looks with a few cards in it.",
    "image": "",
    "link": "https://example.com/affiliate-link-2"
  },
  {
    "id": 3,
    "name": "Sample Product Three",
    "description": "Add your own products using the admin page, then download and replace this file.",
    "image": "",
    "link": "https://example.com/affiliate-link-3"
  },
  {
    "id": 4,
    "name": "Example",
    "description": "HERE",
    "image": "",
    "link": "https://example.com/affiliate-link-2"
  }
];
